"""exceptions.py module."""


class MaxAllowedErrorsReached(Exception):
    """Thrown when maximum numbers of errors reached during GetRecords harvest."""

    pass
